// layout.metadata.ts
import type { Metadata } from "next";

/**
 * Metadata:
 * - 'title': Sets the default page title.
 * - 'description': Provides a brief description of the app.
 */

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};